/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ispace.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LuanChuyen service. Represents a row in the &quot;luanchuyen&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ispace.model.impl.LuanChuyenModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ispace.model.impl.LuanChuyenImpl}.
 * </p>
 *
 * @author PC
 * @see LuanChuyen
 * @see ispace.model.impl.LuanChuyenImpl
 * @see ispace.model.impl.LuanChuyenModelImpl
 * @generated
 */
public interface LuanChuyenModel extends BaseModel<LuanChuyen> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a luan chuyen model instance should use the {@link LuanChuyen} interface instead.
	 */

	/**
	 * Returns the primary key of this luan chuyen.
	 *
	 * @return the primary key of this luan chuyen
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this luan chuyen.
	 *
	 * @param primaryKey the primary key of this luan chuyen
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this luan chuyen.
	 *
	 * @return the ID of this luan chuyen
	 */
	public long getId();

	/**
	 * Sets the ID of this luan chuyen.
	 *
	 * @param id the ID of this luan chuyen
	 */
	public void setId(long id);

	/**
	 * Returns the van ban ID of this luan chuyen.
	 *
	 * @return the van ban ID of this luan chuyen
	 */
	public long getVanBanId();

	/**
	 * Sets the van ban ID of this luan chuyen.
	 *
	 * @param vanBanId the van ban ID of this luan chuyen
	 */
	public void setVanBanId(long vanBanId);

	/**
	 * Returns the kieu van ban of this luan chuyen.
	 *
	 * @return the kieu van ban of this luan chuyen
	 */
	public long getKieuVanBan();

	/**
	 * Sets the kieu van ban of this luan chuyen.
	 *
	 * @param kieuVanBan the kieu van ban of this luan chuyen
	 */
	public void setKieuVanBan(long kieuVanBan);

	/**
	 * Returns the nguoi gui of this luan chuyen.
	 *
	 * @return the nguoi gui of this luan chuyen
	 */
	public long getNguoiGui();

	/**
	 * Sets the nguoi gui of this luan chuyen.
	 *
	 * @param nguoiGui the nguoi gui of this luan chuyen
	 */
	public void setNguoiGui(long nguoiGui);

	/**
	 * Returns the nguoi nhan of this luan chuyen.
	 *
	 * @return the nguoi nhan of this luan chuyen
	 */
	public long getNguoiNhan();

	/**
	 * Sets the nguoi nhan of this luan chuyen.
	 *
	 * @param nguoiNhan the nguoi nhan of this luan chuyen
	 */
	public void setNguoiNhan(long nguoiNhan);

	/**
	 * Returns the ngay gui of this luan chuyen.
	 *
	 * @return the ngay gui of this luan chuyen
	 */
	public Date getNgayGui();

	/**
	 * Sets the ngay gui of this luan chuyen.
	 *
	 * @param ngayGui the ngay gui of this luan chuyen
	 */
	public void setNgayGui(Date ngayGui);

	/**
	 * Returns the ngay nhan of this luan chuyen.
	 *
	 * @return the ngay nhan of this luan chuyen
	 */
	public Date getNgayNhan();

	/**
	 * Sets the ngay nhan of this luan chuyen.
	 *
	 * @param ngayNhan the ngay nhan of this luan chuyen
	 */
	public void setNgayNhan(Date ngayNhan);

	/**
	 * Returns the y kien of this luan chuyen.
	 *
	 * @return the y kien of this luan chuyen
	 */
	@AutoEscape
	public String getYKien();

	/**
	 * Sets the y kien of this luan chuyen.
	 *
	 * @param yKien the y kien of this luan chuyen
	 */
	public void setYKien(String yKien);

	/**
	 * Returns the han xu ly of this luan chuyen.
	 *
	 * @return the han xu ly of this luan chuyen
	 */
	public Date getHanXuLy();

	/**
	 * Sets the han xu ly of this luan chuyen.
	 *
	 * @param hanXuLy the han xu ly of this luan chuyen
	 */
	public void setHanXuLy(Date hanXuLy);

	/**
	 * Returns the y kien phan hoi of this luan chuyen.
	 *
	 * @return the y kien phan hoi of this luan chuyen
	 */
	@AutoEscape
	public String getYKienPhanHoi();

	/**
	 * Sets the y kien phan hoi of this luan chuyen.
	 *
	 * @param yKienPhanHoi the y kien phan hoi of this luan chuyen
	 */
	public void setYKienPhanHoi(String yKienPhanHoi);

	/**
	 * Returns the ngay phan hoi of this luan chuyen.
	 *
	 * @return the ngay phan hoi of this luan chuyen
	 */
	public Date getNgayPhanHoi();

	/**
	 * Sets the ngay phan hoi of this luan chuyen.
	 *
	 * @param ngayPhanHoi the ngay phan hoi of this luan chuyen
	 */
	public void setNgayPhanHoi(Date ngayPhanHoi);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ispace.model.LuanChuyen luanChuyen);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ispace.model.LuanChuyen> toCacheModel();

	@Override
	public ispace.model.LuanChuyen toEscapedModel();

	@Override
	public ispace.model.LuanChuyen toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}