/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ispace.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the NguoiDung service. Represents a row in the &quot;nguoidung&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ispace.model.impl.NguoiDungModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ispace.model.impl.NguoiDungImpl}.
 * </p>
 *
 * @author PC
 * @see NguoiDung
 * @see ispace.model.impl.NguoiDungImpl
 * @see ispace.model.impl.NguoiDungModelImpl
 * @generated
 */
public interface NguoiDungModel extends BaseModel<NguoiDung> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a nguoi dung model instance should use the {@link NguoiDung} interface instead.
	 */

	/**
	 * Returns the primary key of this nguoi dung.
	 *
	 * @return the primary key of this nguoi dung
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this nguoi dung.
	 *
	 * @param primaryKey the primary key of this nguoi dung
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this nguoi dung.
	 *
	 * @return the ID of this nguoi dung
	 */
	public long getId();

	/**
	 * Sets the ID of this nguoi dung.
	 *
	 * @param id the ID of this nguoi dung
	 */
	public void setId(long id);

	/**
	 * Returns the ten of this nguoi dung.
	 *
	 * @return the ten of this nguoi dung
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this nguoi dung.
	 *
	 * @param ten the ten of this nguoi dung
	 */
	public void setTen(String ten);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ispace.model.NguoiDung nguoiDung);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ispace.model.NguoiDung> toCacheModel();

	@Override
	public ispace.model.NguoiDung toEscapedModel();

	@Override
	public ispace.model.NguoiDung toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}