/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ispace.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VanBanDen service. Represents a row in the &quot;vanbanden&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ispace.model.impl.VanBanDenModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ispace.model.impl.VanBanDenImpl}.
 * </p>
 *
 * @author PC
 * @see VanBanDen
 * @see ispace.model.impl.VanBanDenImpl
 * @see ispace.model.impl.VanBanDenModelImpl
 * @generated
 */
public interface VanBanDenModel extends BaseModel<VanBanDen> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a van ban den model instance should use the {@link VanBanDen} interface instead.
	 */

	/**
	 * Returns the primary key of this van ban den.
	 *
	 * @return the primary key of this van ban den
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this van ban den.
	 *
	 * @param primaryKey the primary key of this van ban den
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this van ban den.
	 *
	 * @return the ID of this van ban den
	 */
	public long getId();

	/**
	 * Sets the ID of this van ban den.
	 *
	 * @param id the ID of this van ban den
	 */
	public void setId(long id);

	/**
	 * Returns the so ki hieu of this van ban den.
	 *
	 * @return the so ki hieu of this van ban den
	 */
	@AutoEscape
	public String getSoKiHieu();

	/**
	 * Sets the so ki hieu of this van ban den.
	 *
	 * @param soKiHieu the so ki hieu of this van ban den
	 */
	public void setSoKiHieu(String soKiHieu);

	/**
	 * Returns the so van ban ID of this van ban den.
	 *
	 * @return the so van ban ID of this van ban den
	 */
	public long getSoVanBanId();

	/**
	 * Sets the so van ban ID of this van ban den.
	 *
	 * @param soVanBanId the so van ban ID of this van ban den
	 */
	public void setSoVanBanId(long soVanBanId);

	/**
	 * Returns the loai van ban ID of this van ban den.
	 *
	 * @return the loai van ban ID of this van ban den
	 */
	public long getLoaiVanBanId();

	/**
	 * Sets the loai van ban ID of this van ban den.
	 *
	 * @param loaiVanBanId the loai van ban ID of this van ban den
	 */
	public void setLoaiVanBanId(long loaiVanBanId);

	/**
	 * Returns the date of this van ban den.
	 *
	 * @return the date of this van ban den
	 */
	public Date getDate();

	/**
	 * Sets the date of this van ban den.
	 *
	 * @param date the date of this van ban den
	 */
	public void setDate(Date date);

	/**
	 * Returns the nguoi ki ID of this van ban den.
	 *
	 * @return the nguoi ki ID of this van ban den
	 */
	public long getNguoiKiId();

	/**
	 * Sets the nguoi ki ID of this van ban den.
	 *
	 * @param nguoiKiId the nguoi ki ID of this van ban den
	 */
	public void setNguoiKiId(long nguoiKiId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ispace.model.VanBanDen vanBanDen);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ispace.model.VanBanDen> toCacheModel();

	@Override
	public ispace.model.VanBanDen toEscapedModel();

	@Override
	public ispace.model.VanBanDen toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}