/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the chucdanh service. Represents a row in the &quot;chucdanh&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.test.model.impl.chucdanhModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.test.model.impl.chucdanhImpl}.
 * </p>
 *
 * @author Duy Nguyen
 * @see chucdanh
 * @see com.test.model.impl.chucdanhImpl
 * @see com.test.model.impl.chucdanhModelImpl
 * @generated
 */
public interface chucdanhModel extends BaseModel<chucdanh> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a chucdanh model instance should use the {@link chucdanh} interface instead.
	 */

	/**
	 * Returns the primary key of this chucdanh.
	 *
	 * @return the primary key of this chucdanh
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this chucdanh.
	 *
	 * @param primaryKey the primary key of this chucdanh
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this chucdanh.
	 *
	 * @return the ID of this chucdanh
	 */
	public long getId();

	/**
	 * Sets the ID of this chucdanh.
	 *
	 * @param id the ID of this chucdanh
	 */
	public void setId(long id);

	/**
	 * Returns the ten of this chucdanh.
	 *
	 * @return the ten of this chucdanh
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this chucdanh.
	 *
	 * @param ten the ten of this chucdanh
	 */
	public void setTen(String ten);

	/**
	 * Returns the ma of this chucdanh.
	 *
	 * @return the ma of this chucdanh
	 */
	@AutoEscape
	public String getMa();

	/**
	 * Sets the ma of this chucdanh.
	 *
	 * @param ma the ma of this chucdanh
	 */
	public void setMa(String ma);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.test.model.chucdanh chucdanh);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.test.model.chucdanh> toCacheModel();

	@Override
	public com.test.model.chucdanh toEscapedModel();

	@Override
	public com.test.model.chucdanh toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}