/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the nhom service. Represents a row in the &quot;nhom&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.test.model.impl.nhomModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.test.model.impl.nhomImpl}.
 * </p>
 *
 * @author Duy Nguyen
 * @see nhom
 * @see com.test.model.impl.nhomImpl
 * @see com.test.model.impl.nhomModelImpl
 * @generated
 */
public interface nhomModel extends BaseModel<nhom> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a nhom model instance should use the {@link nhom} interface instead.
	 */

	/**
	 * Returns the primary key of this nhom.
	 *
	 * @return the primary key of this nhom
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this nhom.
	 *
	 * @param primaryKey the primary key of this nhom
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this nhom.
	 *
	 * @return the ID of this nhom
	 */
	public long getId();

	/**
	 * Sets the ID of this nhom.
	 *
	 * @param id the ID of this nhom
	 */
	public void setId(long id);

	/**
	 * Returns the ten of this nhom.
	 *
	 * @return the ten of this nhom
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this nhom.
	 *
	 * @param ten the ten of this nhom
	 */
	public void setTen(String ten);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.test.model.nhom nhom);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.test.model.nhom> toCacheModel();

	@Override
	public com.test.model.nhom toEscapedModel();

	@Override
	public com.test.model.nhom toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}