/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.thuvien.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import com.thuvien.model.Phieumuon;

import com.thuvien.service.PhieumuonService;
import com.thuvien.service.persistence.PhieumuonPersistence;
import com.thuvien.service.persistence.SachPersistence;
import com.thuvien.service.persistence.TheloaiPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the phieumuon remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.thuvien.service.impl.PhieumuonServiceImpl}.
 * </p>
 *
 * @author PC
 * @see com.thuvien.service.impl.PhieumuonServiceImpl
 * @see com.thuvien.service.PhieumuonServiceUtil
 * @generated
 */
public abstract class PhieumuonServiceBaseImpl extends BaseServiceImpl
	implements PhieumuonService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.thuvien.service.PhieumuonServiceUtil} to access the phieumuon remote service.
	 */

	/**
	 * Returns the phieumuon local service.
	 *
	 * @return the phieumuon local service
	 */
	public com.thuvien.service.PhieumuonLocalService getPhieumuonLocalService() {
		return phieumuonLocalService;
	}

	/**
	 * Sets the phieumuon local service.
	 *
	 * @param phieumuonLocalService the phieumuon local service
	 */
	public void setPhieumuonLocalService(
		com.thuvien.service.PhieumuonLocalService phieumuonLocalService) {
		this.phieumuonLocalService = phieumuonLocalService;
	}

	/**
	 * Returns the phieumuon remote service.
	 *
	 * @return the phieumuon remote service
	 */
	public com.thuvien.service.PhieumuonService getPhieumuonService() {
		return phieumuonService;
	}

	/**
	 * Sets the phieumuon remote service.
	 *
	 * @param phieumuonService the phieumuon remote service
	 */
	public void setPhieumuonService(
		com.thuvien.service.PhieumuonService phieumuonService) {
		this.phieumuonService = phieumuonService;
	}

	/**
	 * Returns the phieumuon persistence.
	 *
	 * @return the phieumuon persistence
	 */
	public PhieumuonPersistence getPhieumuonPersistence() {
		return phieumuonPersistence;
	}

	/**
	 * Sets the phieumuon persistence.
	 *
	 * @param phieumuonPersistence the phieumuon persistence
	 */
	public void setPhieumuonPersistence(
		PhieumuonPersistence phieumuonPersistence) {
		this.phieumuonPersistence = phieumuonPersistence;
	}

	/**
	 * Returns the sach local service.
	 *
	 * @return the sach local service
	 */
	public com.thuvien.service.SachLocalService getSachLocalService() {
		return sachLocalService;
	}

	/**
	 * Sets the sach local service.
	 *
	 * @param sachLocalService the sach local service
	 */
	public void setSachLocalService(
		com.thuvien.service.SachLocalService sachLocalService) {
		this.sachLocalService = sachLocalService;
	}

	/**
	 * Returns the sach remote service.
	 *
	 * @return the sach remote service
	 */
	public com.thuvien.service.SachService getSachService() {
		return sachService;
	}

	/**
	 * Sets the sach remote service.
	 *
	 * @param sachService the sach remote service
	 */
	public void setSachService(com.thuvien.service.SachService sachService) {
		this.sachService = sachService;
	}

	/**
	 * Returns the sach persistence.
	 *
	 * @return the sach persistence
	 */
	public SachPersistence getSachPersistence() {
		return sachPersistence;
	}

	/**
	 * Sets the sach persistence.
	 *
	 * @param sachPersistence the sach persistence
	 */
	public void setSachPersistence(SachPersistence sachPersistence) {
		this.sachPersistence = sachPersistence;
	}

	/**
	 * Returns the theloai local service.
	 *
	 * @return the theloai local service
	 */
	public com.thuvien.service.TheloaiLocalService getTheloaiLocalService() {
		return theloaiLocalService;
	}

	/**
	 * Sets the theloai local service.
	 *
	 * @param theloaiLocalService the theloai local service
	 */
	public void setTheloaiLocalService(
		com.thuvien.service.TheloaiLocalService theloaiLocalService) {
		this.theloaiLocalService = theloaiLocalService;
	}

	/**
	 * Returns the theloai remote service.
	 *
	 * @return the theloai remote service
	 */
	public com.thuvien.service.TheloaiService getTheloaiService() {
		return theloaiService;
	}

	/**
	 * Sets the theloai remote service.
	 *
	 * @param theloaiService the theloai remote service
	 */
	public void setTheloaiService(
		com.thuvien.service.TheloaiService theloaiService) {
		this.theloaiService = theloaiService;
	}

	/**
	 * Returns the theloai persistence.
	 *
	 * @return the theloai persistence
	 */
	public TheloaiPersistence getTheloaiPersistence() {
		return theloaiPersistence;
	}

	/**
	 * Sets the theloai persistence.
	 *
	 * @param theloaiPersistence the theloai persistence
	 */
	public void setTheloaiPersistence(TheloaiPersistence theloaiPersistence) {
		this.theloaiPersistence = theloaiPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return Phieumuon.class;
	}

	protected String getModelClassName() {
		return Phieumuon.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = phieumuonPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.thuvien.service.PhieumuonLocalService.class)
	protected com.thuvien.service.PhieumuonLocalService phieumuonLocalService;
	@BeanReference(type = com.thuvien.service.PhieumuonService.class)
	protected com.thuvien.service.PhieumuonService phieumuonService;
	@BeanReference(type = PhieumuonPersistence.class)
	protected PhieumuonPersistence phieumuonPersistence;
	@BeanReference(type = com.thuvien.service.SachLocalService.class)
	protected com.thuvien.service.SachLocalService sachLocalService;
	@BeanReference(type = com.thuvien.service.SachService.class)
	protected com.thuvien.service.SachService sachService;
	@BeanReference(type = SachPersistence.class)
	protected SachPersistence sachPersistence;
	@BeanReference(type = com.thuvien.service.TheloaiLocalService.class)
	protected com.thuvien.service.TheloaiLocalService theloaiLocalService;
	@BeanReference(type = com.thuvien.service.TheloaiService.class)
	protected com.thuvien.service.TheloaiService theloaiService;
	@BeanReference(type = TheloaiPersistence.class)
	protected TheloaiPersistence theloaiPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private PhieumuonServiceClpInvoker _clpInvoker = new PhieumuonServiceClpInvoker();
}