/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.thuvien.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.thuvien.model.Sach;
import com.thuvien.model.SachModel;
import com.thuvien.model.SachSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Sach service. Represents a row in the &quot;sach&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.thuvien.model.SachModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SachImpl}.
 * </p>
 *
 * @author PC
 * @see SachImpl
 * @see com.thuvien.model.Sach
 * @see com.thuvien.model.SachModel
 * @generated
 */
@JSON(strict = true)
public class SachModelImpl extends BaseModelImpl<Sach> implements SachModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sach model instance should use the {@link com.thuvien.model.Sach} interface instead.
	 */
	public static final String TABLE_NAME = "sach";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "ten", Types.VARCHAR },
			{ "masach", Types.VARCHAR },
			{ "soluong", Types.BIGINT },
			{ "theloaiId", Types.BIGINT },
			{ "ke", Types.VARCHAR },
			{ "tang", Types.VARCHAR },
			{ "tacgia", Types.VARCHAR },
			{ "nhaxuatban", Types.VARCHAR },
			{ "soluongconlai", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table sach (id LONG not null primary key,ten VARCHAR(75) null,masach VARCHAR(75) null,soluong LONG,theloaiId LONG,ke VARCHAR(75) null,tang VARCHAR(75) null,tacgia VARCHAR(75) null,nhaxuatban VARCHAR(75) null,soluongconlai LONG)";
	public static final String TABLE_SQL_DROP = "drop table sach";
	public static final String ORDER_BY_JPQL = " ORDER BY sach.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY sach.id ASC";
	public static final String DATA_SOURCE = "qlythuvienDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.thuvien.model.Sach"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.thuvien.model.Sach"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Sach toModel(SachSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Sach model = new SachImpl();

		model.setId(soapModel.getId());
		model.setTen(soapModel.getTen());
		model.setMaSach(soapModel.getMaSach());
		model.setSoLuong(soapModel.getSoLuong());
		model.setTheLoai(soapModel.getTheLoai());
		model.setKe(soapModel.getKe());
		model.setTang(soapModel.getTang());
		model.setTacGia(soapModel.getTacGia());
		model.setNhaXuatBan(soapModel.getNhaXuatBan());
		model.setSoLuongConlai(soapModel.getSoLuongConlai());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Sach> toModels(SachSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Sach> models = new ArrayList<Sach>(soapModels.length);

		for (SachSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.thuvien.model.Sach"));

	public SachModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Sach.class;
	}

	@Override
	public String getModelClassName() {
		return Sach.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("ten", getTen());
		attributes.put("maSach", getMaSach());
		attributes.put("soLuong", getSoLuong());
		attributes.put("theLoai", getTheLoai());
		attributes.put("ke", getKe());
		attributes.put("tang", getTang());
		attributes.put("tacGia", getTacGia());
		attributes.put("nhaXuatBan", getNhaXuatBan());
		attributes.put("soLuongConlai", getSoLuongConlai());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String ten = (String)attributes.get("ten");

		if (ten != null) {
			setTen(ten);
		}

		String maSach = (String)attributes.get("maSach");

		if (maSach != null) {
			setMaSach(maSach);
		}

		Long soLuong = (Long)attributes.get("soLuong");

		if (soLuong != null) {
			setSoLuong(soLuong);
		}

		Long theLoai = (Long)attributes.get("theLoai");

		if (theLoai != null) {
			setTheLoai(theLoai);
		}

		String ke = (String)attributes.get("ke");

		if (ke != null) {
			setKe(ke);
		}

		String tang = (String)attributes.get("tang");

		if (tang != null) {
			setTang(tang);
		}

		String tacGia = (String)attributes.get("tacGia");

		if (tacGia != null) {
			setTacGia(tacGia);
		}

		String nhaXuatBan = (String)attributes.get("nhaXuatBan");

		if (nhaXuatBan != null) {
			setNhaXuatBan(nhaXuatBan);
		}

		Long soLuongConlai = (Long)attributes.get("soLuongConlai");

		if (soLuongConlai != null) {
			setSoLuongConlai(soLuongConlai);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	@Override
	public void setTen(String ten) {
		_ten = ten;
	}

	@JSON
	@Override
	public String getMaSach() {
		if (_maSach == null) {
			return StringPool.BLANK;
		}
		else {
			return _maSach;
		}
	}

	@Override
	public void setMaSach(String maSach) {
		_maSach = maSach;
	}

	@JSON
	@Override
	public long getSoLuong() {
		return _soLuong;
	}

	@Override
	public void setSoLuong(long soLuong) {
		_soLuong = soLuong;
	}

	@JSON
	@Override
	public long getTheLoai() {
		return _theLoai;
	}

	@Override
	public void setTheLoai(long theLoai) {
		_theLoai = theLoai;
	}

	@JSON
	@Override
	public String getKe() {
		if (_ke == null) {
			return StringPool.BLANK;
		}
		else {
			return _ke;
		}
	}

	@Override
	public void setKe(String ke) {
		_ke = ke;
	}

	@JSON
	@Override
	public String getTang() {
		if (_tang == null) {
			return StringPool.BLANK;
		}
		else {
			return _tang;
		}
	}

	@Override
	public void setTang(String tang) {
		_tang = tang;
	}

	@JSON
	@Override
	public String getTacGia() {
		if (_tacGia == null) {
			return StringPool.BLANK;
		}
		else {
			return _tacGia;
		}
	}

	@Override
	public void setTacGia(String tacGia) {
		_tacGia = tacGia;
	}

	@JSON
	@Override
	public String getNhaXuatBan() {
		if (_nhaXuatBan == null) {
			return StringPool.BLANK;
		}
		else {
			return _nhaXuatBan;
		}
	}

	@Override
	public void setNhaXuatBan(String nhaXuatBan) {
		_nhaXuatBan = nhaXuatBan;
	}

	@JSON
	@Override
	public long getSoLuongConlai() {
		return _soLuongConlai;
	}

	@Override
	public void setSoLuongConlai(long soLuongConlai) {
		_soLuongConlai = soLuongConlai;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Sach.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Sach toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Sach)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SachImpl sachImpl = new SachImpl();

		sachImpl.setId(getId());
		sachImpl.setTen(getTen());
		sachImpl.setMaSach(getMaSach());
		sachImpl.setSoLuong(getSoLuong());
		sachImpl.setTheLoai(getTheLoai());
		sachImpl.setKe(getKe());
		sachImpl.setTang(getTang());
		sachImpl.setTacGia(getTacGia());
		sachImpl.setNhaXuatBan(getNhaXuatBan());
		sachImpl.setSoLuongConlai(getSoLuongConlai());

		sachImpl.resetOriginalValues();

		return sachImpl;
	}

	@Override
	public int compareTo(Sach sach) {
		long primaryKey = sach.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Sach)) {
			return false;
		}

		Sach sach = (Sach)obj;

		long primaryKey = sach.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Sach> toCacheModel() {
		SachCacheModel sachCacheModel = new SachCacheModel();

		sachCacheModel.id = getId();

		sachCacheModel.ten = getTen();

		String ten = sachCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			sachCacheModel.ten = null;
		}

		sachCacheModel.maSach = getMaSach();

		String maSach = sachCacheModel.maSach;

		if ((maSach != null) && (maSach.length() == 0)) {
			sachCacheModel.maSach = null;
		}

		sachCacheModel.soLuong = getSoLuong();

		sachCacheModel.theLoai = getTheLoai();

		sachCacheModel.ke = getKe();

		String ke = sachCacheModel.ke;

		if ((ke != null) && (ke.length() == 0)) {
			sachCacheModel.ke = null;
		}

		sachCacheModel.tang = getTang();

		String tang = sachCacheModel.tang;

		if ((tang != null) && (tang.length() == 0)) {
			sachCacheModel.tang = null;
		}

		sachCacheModel.tacGia = getTacGia();

		String tacGia = sachCacheModel.tacGia;

		if ((tacGia != null) && (tacGia.length() == 0)) {
			sachCacheModel.tacGia = null;
		}

		sachCacheModel.nhaXuatBan = getNhaXuatBan();

		String nhaXuatBan = sachCacheModel.nhaXuatBan;

		if ((nhaXuatBan != null) && (nhaXuatBan.length() == 0)) {
			sachCacheModel.nhaXuatBan = null;
		}

		sachCacheModel.soLuongConlai = getSoLuongConlai();

		return sachCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", maSach=");
		sb.append(getMaSach());
		sb.append(", soLuong=");
		sb.append(getSoLuong());
		sb.append(", theLoai=");
		sb.append(getTheLoai());
		sb.append(", ke=");
		sb.append(getKe());
		sb.append(", tang=");
		sb.append(getTang());
		sb.append(", tacGia=");
		sb.append(getTacGia());
		sb.append(", nhaXuatBan=");
		sb.append(getNhaXuatBan());
		sb.append(", soLuongConlai=");
		sb.append(getSoLuongConlai());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.thuvien.model.Sach");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maSach</column-name><column-value><![CDATA[");
		sb.append(getMaSach());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soLuong</column-name><column-value><![CDATA[");
		sb.append(getSoLuong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>theLoai</column-name><column-value><![CDATA[");
		sb.append(getTheLoai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ke</column-name><column-value><![CDATA[");
		sb.append(getKe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tang</column-name><column-value><![CDATA[");
		sb.append(getTang());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tacGia</column-name><column-value><![CDATA[");
		sb.append(getTacGia());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nhaXuatBan</column-name><column-value><![CDATA[");
		sb.append(getNhaXuatBan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soLuongConlai</column-name><column-value><![CDATA[");
		sb.append(getSoLuongConlai());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Sach.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { Sach.class };
	private long _id;
	private String _ten;
	private String _maSach;
	private long _soLuong;
	private long _theLoai;
	private String _ke;
	private String _tang;
	private String _tacGia;
	private String _nhaXuatBan;
	private long _soLuongConlai;
	private Sach _escapedModel;
}